trigger:
  branches:
    include: [main]

variables:
  azureSubscription: 'devops-sp-connection'
  acrName: 'acrdevopspraca45e7fbf'
  webAppName: 'webapp-devops-prac-a45e7fbf'
  buildId: $(Build.BuildId)
  dockerTag: '$(buildId)'

stages:
- stage: Terraform
  jobs:
  - job: TerraformApply
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'
    - script: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="acr_name=$(acrName)" -var="web_app_name=$(webAppName)"
      displayName: 'Terraform Init and Apply'
      env:
        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
        ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        ARM_TENANT_ID: $(AZURE_TENANT_ID)

- stage: BuildAndPush
  dependsOn: Terraform
  jobs:
  - job: BuildPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(azureSubscription)'
        repository: '$(acrName)/$(webAppName)'
        command: buildAndPush
        Dockerfile: 'app/Dockerfile'
        tags: |
          latest
          $(dockerTag)

- stage: DeployWebApp
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(webAppName)'
        imageName: '$(acrName).azurecr.io/$(webAppName):$(dockerTag)'
